version: "3"
services:
  dreamdrugs-frontend:
    restart: always
    build: ./frontend
    volumes:
      - image-uploads:/uploads

  dreamdrugs-backend:
    restart: always
    build: ./backend
    volumes:
      - image-uploads:/uploads

  database:
    restart: always
    image: redis

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - dreamdrugs-backend
      - dreamdrugs-frontend
    networks:
      default:
        aliases:
          - dreamdrugs.com
          - api.dreamdrugs.com
    volumes:
      - image-uploads:/uploads

volumes:
  image-uploads:
