# What port should the application load balancer serve on.
hostPort: 80

# The GCE project. The GCR images must live under that namespace.
projectId: dreambox-261818

# What docker image tag for the images to pull.
tag: latest
