---
{{ if .Values.development }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dreamdrugs.fullname" . }}-cloudflare-secret
  labels:
    app: {{ template "dreamdrugs.fullname" . }}-kubernetes-cloudflare-sync
type: Opaque
data:
  email: {{ .Values.cloudflare.email | b64enc | quote }}
  api-key: {{ .Values.cloudflare.globalApiKey | b64enc | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dreamdrugs.fullname" . }}-kubernetes-cloudflare-sync
  labels:
    app: {{ template "dreamdrugs.fullname" . }}-kubernetes-cloudflare-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "dreamdrugs.fullname" . }}-kubernetes-cloudflare-sync
  template:
    metadata:
      labels:
        app: {{ template "dreamdrugs.fullname" . }}-kubernetes-cloudflare-sync
    spec:
      serviceAccountName: {{ template "dreamdrugs.fullname" . }}-kubernetes-cloudflare-sync
      containers:
        - name: kubernetes-cloudflare-sync
          image: gcr.io/dreamdrugs/kubernetes-cloudflare-sync
          args:
            - --dns-name=kubernetes.{{ .Values.domain }}
          env:
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "dreamdrugs.fullname" . }}-cloudflare-secret
                  key: api-key
            - name: CF_API_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ template "dreamdrugs.fullname" . }}-cloudflare-secret
                  key: email
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dreamdrugs.fullname" . }}-kubernetes-cloudflare-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "dreamdrugs.fullname" . }}-kubernetes-cloudflare-sync
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "dreamdrugs.fullname" . }}-kubernetes-cloudflare-sync-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "dreamdrugs.fullname" . }}-kubernetes-cloudflare-sync
subjects:
  - kind: ServiceAccount
    name: {{ template "dreamdrugs.fullname" . }}-kubernetes-cloudflare-sync
    namespace: default
{{ end }}
