apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dreamdrugs.fullname" . }}-frontend
  labels:
    app: {{ template "dreamdrugs.fullname" . }}-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ template "dreamdrugs.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ template "dreamdrugs.fullname" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontendImage }}
          env:
          - name: NODE_ENV
            value: 'production'
          - name: REDIS_HOST
            value: 'redis-master.default.svc.cluster.local'
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: redis-password

          ports:
          - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "dreamdrugs.fullname" . }}-frontend
spec:
  type: NodePort
  selector:
    app: {{ template "dreamdrugs.fullname" . }}-frontend
  ports:
  - protocol: TCP
    port: 3030
    targetPort: 3000
