# The GCE project. The GCR images must live under that namespace.
projectId: dreamdrugs

# What docker image tag for the images to pull.
tag: latest

# What domain will the application live in
domain: dreamdrugs.art

# The images to deploy.
backendImage: gcr.io/dreamdrugs/backend:0.1.0
frontendImage: gcr.io/dreamdrugs/frontend:0.1.0

# The environment for each component, either 'production' or 'development'.
development: false
