apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    deployment: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: backend
  template:
    metadata:
      labels:
        pod: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/dreambox-261818/backend:latest
          env:
            - name: ENV
              value: 'production'
            - name: DEBUG
              value: '0'
            - name: FLASKPORT
              value: '4000'
            - name: GUNICORNPORT
              value: '8000'
